// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlinefoodDeliverySystem.Models;

#nullable disable

namespace OnlinefoodDeliverySystem.Migrations
{
    [DbContext(typeof(FoodOrderingDbContext))]
    [Migration("20250921120830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OnlinefoodDeliverySystem.Models.FoodData", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("foodItem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("restaurantName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("totalPrice")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.ToTable("FoodOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
